# Generated by Django 3.2.6 on 2021-08-30 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='first_name',
            field=models.CharField(max_length=250, verbose_name='Nomme'),
        ),
    ]
