# Generated by Django 3.2.6 on 2021-08-30 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210830_1844'),
    ]

    operations = [
        migrations.RenameField(
            model_name='colaborador',
            old_name='emailInstitucional',
            new_name='address_email',
        ),
    ]
