# Generated by Django 3.2.6 on 2021-08-30 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_emailinstitucional_colaborador_address_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colaborador',
            name='address_email',
        ),
        migrations.AddField(
            model_name='colaborador',
            name='email_user',
            field=models.EmailField(default='unifop@fiponline.edu.br', max_length=250, verbose_name='Email Institucional'),
        ),
    ]
