# Generated by Django 3.2.6 on 2021-08-30 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210830_1847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colaborador',
            name='email_user',
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='email',
            field=models.EmailField(default='unifop@fiponline.edu.br', max_length=250, verbose_name='Email Institucional'),
        ),
    ]
